### ISSUE TITLE
Error of the picosdk-c-examples

### ISSUE THREAD

**Issue by forsakenfirer** [picotech/picosdk-c-examples#2]
For PicoScope 2204A,I used the ubuntu server 16.04 to installed libps2000 (version 2.4.0-3r09).
Sometimes,When I running the demo ps2000con from picosdk-c-examples used collect_fast_streaming_triggered2，that the error happened :

Collect streaming...
Data is written to disk file (fast_streaming_trig_data2.txt)
Press a key to start
OK: 1

Application buffer full - stopping data collection.
*** Error in `./pico': munmap_chunk(): invalid pointer: 0x000000000166b6b0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fed56e317e5]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x1a8)[0x7fed56e3e698]
/opt/picoscope/lib/libps2000.so.2(+0x15873)[0x7fed57199873]
/opt/picoscope/lib/libps2000.so.2(+0x15969)[0x7fed57199969]
/opt/picoscope/lib/libps2000.so.2(+0x1f850)[0x7fed571a3850]
/opt/picoscope/lib/libps2000.so.2(+0xea58)[0x7fed57192a58]
/opt/picoscope/lib/libps2000.so.2(+0x1c864)[0x7fed571a0864]
/opt/picoscope/lib/libps2000.so.2(ps2000_stop+0x27)[0x7fed571a24e7]
./pico(collect_fast_streaming_triggered2+0x236)[0x40460e]
./pico(main+0x244)[0x4058e1]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fed56dda830]
./pico(_start+0x29)[0x401e89]
======= Memory map: ========
00400000-00407000 r-xp 00000000 08:01 278288                             /home/firer/pico/build/pico
00606000-00607000 r--p 00006000 08:01 278288                             /home/firer/pico/build/pico
00607000-00608000 rw-p 00007000 08:01 278288                             /home/firer/pico/build/pico
00608000-0060e000 rw-p 00000000 00:00 0
0160e000-0225b000 rw-p 00000000 00:00 0                                  [heap]
7fed4c000000-7fed4c021000 rw-p 00000000 00:00 0
7fed4c021000-7fed50000000 ---p 00000000 00:00 0
7fed53718000-7fed53719000 ---p 00000000 00:00 0
...

**Comment by hsmistry** [comment]
@forsakenfirer, is the trigger condition being met during the data collection process?
