### ISSUE TITLE
picosdk-c-examples not finding symbols

### ISSUE THREAD

**Issue by CumminsBob** [picotech/picosdk-c-examples#3]
### Setup

* Example filename: ps4000aStreaming.cpp
* IDE/Compiler being used: See Info below, Visual Studio 2017
* Pico Technology device model: PicoScope 4824
* Driver name, version number and platform (32/64-bit): Precision 5530, 64bit
* Operating system:  Microsoft Windows 10 Enterprise, OS:10.0.16299
* USB port type	(e.g. 2.0): 3.1

Microsoft Visual Studio Community 2017 
Version 15.8.5
VisualStudio.15.Release/15.8.5+28010.2036
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA109
Microsoft Visual C++ 2017

ASP.NET and Web Tools 2017   15.8.05085.0
ASP.NET and Web Tools 2017

C# Tools   2.9.0-beta8-63208-01
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

Visual Basic Tools   2.9.0-beta8-63208-01
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

### Description

I can get the software to compile, then I am able to build the solution, but when I execute it, this is what I get.  I know it is something dumb that I am missing... :

'ReStreaming.exe' (Win32): Loaded 'C:\Users\kv993\source\repos\ReStreaming\x64\Debug\ReStreaming.exe'. Symbols loaded.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Program Files\Pico Technology\SDK\lib\ps4000a.dll'. Module was built without symbols.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\setupapi.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\powrprof.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140d.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbased.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.16299.665_none_887c2a984ab8b351\comctl32.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. Cannot find or open the PDB file.
The thread 0x1b68 has exited with code 0 (0x0).
'ReStreaming.exe' (Win32): Loaded 'C:\Program Files\Pico Technology\SDK\lib\picoipp.dll'. Module was built without symbols.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\msctf.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\dwmapi.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\wintrust.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\msasn1.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\crypt32.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\TextInputFramework.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\CoreMessaging.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\CoreUIComponents.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\ntmarta.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Unloaded 'C:\Windows\System32\WinTypes.dll'
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\winusb.dll'. Cannot find or open the PDB file.
'ReStreaming.exe' (Win32): Unloaded 'C:\Windows\System32\winusb.dll'
'ReStreaming.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. Cannot find or open the PDB file.
The thread 0x397c has exited with code 0 (0x0).
The thread 0x38d8 has exited with code -1073741510 (0xc000013a).
The thread 0x144c has exited with code -1073741510 (0xc000013a).
The thread 0xc44 has exited with code -1073741510 (0xc000013a).
The thread 0xd7c has exited with code -1073741510 (0xc000013a).
The thread 0x3260 has exited with code -1073741510 (0xc000013a).
The thread 0x4e8 has exited with code -1073741510 (0xc000013a).
The thread 0x33f8 has exited with code -1073741749 (0xc000004b).
The program '[1876] ReStreaming.exe' has exited with code -1073741510 (0xc000013a).

#### Steps to reproduce the issue

Use one of two methods to describe the issue:

1. A list of steps to reproduce the issue. 
1. A natural language description of what you were doing when the issue occurred if you are unable to work out what the steps are. 

### Notes

The main point is that it is telling me that the
'ReStreaming.exe' (Win32): Loaded 'C:\Program Files\Pico Technology\SDK\lib\ps4000a.dll'. Module was built without symbols.
and
'ReStreaming.exe' (Win32): Loaded 'C:\Program Files\Pico Technology\SDK\lib\picoipp.dll'. Module was built without symbols.

I have been working this and it keeps coming down to these issues as my root problem.

Downloaded the source and installed the SDK last week.  I was very specific about getting the 64bit version.

Robert
kv993@cummins.com

**Comment by hsmistry** [comment]
@CumminsBob, which version of the PicoSDK have you installed?
