### ISSUE TITLE
Build Application to read value in MacOS by Objective-C

### ISSUE THREAD

**Issue by trieutuanvnu** [picotech/picosdk-c-examples#4]
Hi Team,

Im writing application to read value in MacOS by Objective-C. Is there any way to build it, do you have any example using Objective-C. Since I saw there're a application supported MacOS, what's language you're using.

**Comment by hsmistry** [comment]
Hi @trieutuanvnu, unfortunately we do not have an Objective-C examples. The PicoScope 6 software is a .NET application that has been adapted to run on macOS.

**Comment by hsmistry** [comment]
Hi @trieutuanvnu, it might be possible to create an Objective C app to communicate with the TC-08 and PT-104 temperature data loggers.

If you are referring to the PicoLog data logging software I am unable to provide much information about it.

**Comment by trieutuanvnu** [comment]
Hi @hsmistry, thanks for your information. I got library after install PicoLog SW  in MacOS. Could you share how to add this .dylib into Objective C/XCode project and use it as external lib to create a Objective C app to read data from TC-08. It's would be good if you can help to create a sample, i think it will support alot for other users also.

**Comment by trieutuanvnu** [comment]
One more think incase I want to use C in MacOS, there're only .dylib, how can can import  "usbtc08.h"

**Comment by hsmistry** [comment]
Hi @trieutuanvnu, it should be possible to add the location of the usbtc08.h and usbtc08.dylib to an XCode project. 

If you copy the usbtc08Con.c file into the linux-build-files folder you can build the console app from command line. You will need to copy the usbtc08.dylib file to the /opt/picoscope/lib directory or you can change the configure.ac file to point to another directory.

If you need further support, I would suggest e-mailing us at support@picotech.com
