### ISSUE TITLE
void setResolution() crash

### ISSUE THREAD

**Issue by dserbu** [picotech/picosdk-c-examples#5]
* Filename: ps4000aCon.c
* Pico Technology device model: 4444a
* Operating system: ubuntu
* USB port typ: 3.0

When resolution is changed in example file program will stop.

> Select device resolution:
1: 12 bits
2: 14 bits
Resolution [1...2]: 1
*** stack smashing detected ***: ./ps4000aCon terminated
Aborted (core dumped)

**Comment by hsmistry** [comment]
Thanks @dserbu We will investigate and get back to you.

**Comment by hsmistry** [comment]
Hi @dserbu, this has been fixed in Changeset 7810e5b.
